name: Deploy application1

on:
  push:
    branches:
      - gh-pages-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to application1 directory
        run: cd application1

      - name: Install dependencies
        working-directory: application1
        run: npm install

      - name: Build site
        working-directory: application1
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: application1/build/
          publish_branch: gh-pages
          destination_dir: application1
