name: Deploy svelte-master

on:
  push:
    branches:
      - svelte-master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to Svelte-POC directory
        run: cd Svelte-POC

      - name: Install dependencies
        working-directory: Svelte-POC
        run: npm install

      - name: Build site
        working-directory: Svelte-POC
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Svelte-POC/dist/
          publish_branch: gh-pages
          destination_dir: echarts